a = input("Write Seven fruits names: ")
fruits = a.split(", ")
print(f"THE Fruits names are: {fruits}")

# another way to solve this problem
fruits = []
f1 = input("Enter first fruit name: ")
fruits.append(f1)
f2 = input("Enter second fruit name: ")
fruits.append(f2)
f3 = input("Enter third fruit name: ")
fruits.append(f3)
f4 = input("Enter fourth fruit name: ")
fruits.append(f4)
f5 = input("Enter fifth fruit name: ")
fruits.append(f5)
f6 = input("Enter sixth fruit name: ")
fruits.append(f6)
f7 = input("Enter seventh fruit name: ")
fruits.append(f7)
print(f"THE Fruits names are: {fruits}")